# Generated by Django 5.0.2 on 2024-02-18 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puechace_quality', models.FloatField(default=0)),
                ('sell_price', models.FloatField(default=0)),
                ('total_balance_quality', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('purchace', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.purchace')),
                ('sell', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.sell')),
            ],
            options={
                'verbose_name_plural': 'Inventorys',
            },
        ),
    ]
