# Generated by Django 5.0.2 on 2024-02-19 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': '6. Inventorys'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '3. Products'},
        ),
        migrations.AlterModelOptions(
            name='purchace',
            options={'verbose_name_plural': '4. Purchaces'},
        ),
        migrations.AlterModelOptions(
            name='sell',
            options={'verbose_name_plural': '5. Sells'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name_plural': '2. Units'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name_plural': '1. Vendors'},
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='sell_price',
            new_name='sell_quality',
        ),
    ]
