# Generated by Django 5.0.2 on 2024-03-08 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_inventory_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='puechace_quality',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='purchace',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.purchace'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sell',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sell'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sell_quality',
            field=models.FloatField(default=0, null=True),
        ),
    ]
