# Generated by Django 5.0.2 on 2024-03-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_inventory_puechace_quality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='total_amount',
            field=models.FloatField(editable=False),
        ),
    ]
