# Generated by Django 5.0.2 on 2024-03-08 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_sell_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=50)),
                ('customer_mobile', models.CharField(max_length=20)),
                ('customer_address', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sell',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='customer_mobile',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='sell',
            name='coustomer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.coustomer'),
        ),
    ]
