# Generated by Django 5.0.2 on 2024-03-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_coustomer_options_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coustomer',
            options={'verbose_name_plural': '2. Coustomers'},
        ),
    ]
